pub use fs_meta::product_model::routes::{
    METHOD_FIND, METHOD_QUERY, METHOD_SINK_QUERY, METHOD_SINK_QUERY_PROXY,
    METHOD_SINK_ROOTS_CONTROL, METHOD_SINK_STATUS, METHOD_SOURCE_FIND, METHOD_SOURCE_RESCAN,
    METHOD_SOURCE_RESCAN_CONTROL, METHOD_SOURCE_ROOTS_CONTROL, METHOD_SOURCE_STATUS, METHOD_STREAM,
    ROUTE_KEY_EVENTS, ROUTE_KEY_FACADE_CONTROL, ROUTE_KEY_FORCE_FIND, ROUTE_KEY_QUERY,
    ROUTE_KEY_SINK_QUERY_INTERNAL, ROUTE_KEY_SINK_QUERY_PROXY, ROUTE_KEY_SINK_ROOTS_CONTROL,
    ROUTE_KEY_SINK_STATUS_INTERNAL, ROUTE_KEY_SOURCE_FIND_INTERNAL,
    ROUTE_KEY_SOURCE_RESCAN_CONTROL, ROUTE_KEY_SOURCE_RESCAN_INTERNAL,
    ROUTE_KEY_SOURCE_ROOTS_CONTROL, ROUTE_KEY_SOURCE_STATUS_INTERNAL, ROUTE_TOKEN_FS_META,
    ROUTE_TOKEN_FS_META_EVENTS, ROUTE_TOKEN_FS_META_INTERNAL, default_route_bindings,
    sink_query_request_route_for, sink_query_route_bindings_for, sink_query_route_key_for,
    sink_roots_control_route_key_for, sink_roots_control_stream_route_for,
    source_find_request_route_for, source_find_route_bindings_for, source_find_route_key_for,
    source_rescan_request_route_for, source_rescan_route_bindings_for, source_rescan_route_key_for,
    source_roots_control_route_key_for, source_roots_control_stream_route_for,
};
